import {
  ArchiveIcon,
  BookOpen,
  Calculator,
  ChefHat,
  Cog,
  Container,
  LineChart,
  Menu,
  Settings,
  ShoppingCart,
  Soup,
  Table,
  User,
  LayoutDashboard,
  Carrot,
  Package2,
  Package,
  Package2Icon,
} from "lucide-react";

import { FiLayout, FiShoppingCart } from "react-icons/fi";

export const navigationRoute = [
  {
    label: "Dashboard",
    icon: FiLayout,
    href: "/dashboard",
    color: "text-violet-500",
    isFileMenu: false,
  },

  {
    label: "Procurements",
    icon: FiShoppingCart,
    href: "/purchase",
    color: "text-pink-700",
    isFileMenu: true,
    subMenu: [
      {
        label: "Ingredients",
        icon: Carrot,
        href: "/ingredients",
        color: "text-pink-700",
        isFileMenu: true,
      },
      {
        label: "Category",
        icon: Package2Icon,
        href: "/category",
        color: "text-pink-700",
        isFileMenu: true,
      },

      {
        label: "Sub Category",
        icon: Package,
        href: "/sub-category",
        color: "text-pink-700",
        isFileMenu: true,
      },
      {
        label: "Size",
        icon: ShoppingCart,
        href: "/size",
        color: "text-pink-700",
        isFileMenu: true,
      },
      {
        label: "Unit",
        icon: ShoppingCart,
        href: "/unit",
        color: "text-pink-700",
        isFileMenu: true,
      },
      {
        label: "Brand",
        icon: ShoppingCart,
        href: "/brand",
        color: "text-pink-700",
        isFileMenu: true,
      },
      {
        label: "Divider",
        icon: ShoppingCart,
        href: "divider",
        color: "text-pink-700",
        isFileMenu: true,
      },
      {
        label: "Purchase",
        icon: ShoppingCart,
        href: "/purchase",
        color: "text-pink-700",
        isFileMenu: true,
      },
      {
        label: "Divider",
        icon: ShoppingCart,
        href: "divider",
        color: "text-pink-700",
        isFileMenu: true,
      },
      {
        label: "Grn",
        icon: ShoppingCart,
        href: "/grn",
        color: "text-pink-700",
        isFileMenu: true,
      },
      {
        label: "Divider",
        icon: ShoppingCart,
        href: "divider",
        color: "text-pink-700",
        isFileMenu: true,
      },
      {
        label: "RTV",
        icon: ShoppingCart,
        href: "/rtv",
        color: "text-pink-700",
        isFileMenu: true,
      },
      {
        label: "Divider",
        icon: ShoppingCart,
        href: "divider",
        color: "text-pink-700",
        isFileMenu: true,
      },
      {
        label: "Supplier",
        icon: ShoppingCart,
        href: "/supplier",
        color: "text-pink-700",
        isFileMenu: true,
      },
    ],
  },
  {
    label: "Menu & Orders",
    icon: Soup,
    href: "/menu",
    color: "text-orange-700",
    isFileMenu: true,
    subMenu: [
      {
        label: "Procurements",
        icon: ShoppingCart,
        href: "/purchase",
        color: "text-pink-700",
        isFileMenu: true,
      },
      {
        label: "Procurements",
        icon: ShoppingCart,
        href: "/purchase",
        color: "text-pink-700",
        isFileMenu: true,
      },
    ],
  },
  {
    label: "Table & Booking",
    icon: Container,
    href: "/booking",
    color: "text-sky-500",
    isFileMenu: true,
  },
  {
    label: "Accounts",
    icon: Calculator,
    href: "/accounts",
    color: "text-green-500",
    isFileMenu: true,
  },
  {
    label: "Inventory",
    icon: ArchiveIcon,
    href: "/inventory",
    color: "text-purple-500",
    isFileMenu: false,
  },
  {
    label: "Reports",
    icon: LineChart,
    href: "/reports",
    color: "text-pink-500",
    isFileMenu: false,
  },
  {
    label: "User",
    icon: User,
    href: "/user",
    color: "text-emerald-500",
    isFileMenu: false,
  },
  {
    label: "Setting",
    icon: Settings,
    href: "/settings",
    color: "text-zinc-200",
    isFileMenu: false,
  },
];
