import {
  ArchiveIcon,
  BookOpen,
  Calculator,
  ChefHat,
  Cog,
  Container,
  LineChart,
  Menu,
  Settings,
  ShoppingCart,
  Soup,
  Table,
  User,
  LayoutDashboard,
  Carrot,
  Package2,
  Package,
  Package2Icon,
  PencilRuler,
  Boxes,
  BadgeCheck,
  ScrollText,
  Undo2,
  User2,
  FileText,
  LayoutList,
  FilePlus2,
  PieChart,
  Trash2,
  SlidersHorizontal,
  Wallet2,
  BookPlus,
  FileMinus,
  Book,
  Landmark,
  SmartphoneCharging,
  UserCog,
  FolderCog,
  SquareStack,
} from "lucide-react";

export const navigationRoute = [
  {
    label: "Dashboard",
    icon: LayoutDashboard,
    href: "/dashboard",
    color: "text-violet-500",
    bgColor: "text-violet-500/10",
    isFileMenu: false,
  },
  {
    label: "Procurements",
    icon: ShoppingCart,
    href: "/procurements",
    color: "text-pink-700",
    bgColor: "text-pink-700/10",
    isFileMenu: true,
    subMenu: [
      {
        label: "Ingredients",
        icon: Carrot,
        href: "/ingredients",
        color: "text-pink-700",
        bgColor: "text-pink-700/10",
        isFileMenu: true,
        subMenu: [
          {
            label: "Ingredients List",
            icon: LayoutList,
            href: "/ingredients",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },
          {
            label: "Category",
            icon: Package2Icon,
            href: "/ingredients/category",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },

          {
            label: "Sub Category",
            icon: Package,
            href: "/ingredients/sub-category",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },
          {
            label: "Size",
            icon: PencilRuler,
            href: "/ingredients/size",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },
          {
            label: "Unit",
            icon: SquareStack,
            href: "/ingredients/unit",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },
          {
            label: "Brand",
            icon: BadgeCheck,
            href: "/ingredients/brand",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },
        ],
      },

      {
        label: "Purchase",
        icon: ShoppingCart,
        href: "/purchase",
        color: "text-pink-700",
        bgColor: "text-pink-700/10",
        isFileMenu: true,
        subMenu: [
          {
            label: "All Purchase",
            icon: LayoutList,
            href: "/category",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },
          {
            label: "New Purchase",
            icon: FilePlus2,
            href: "/category",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },

          {
            label: "Analytics",
            icon: PieChart,
            href: "/sub-category",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },
        ],
      },

      {
        label: "Grn",
        icon: ScrollText,
        href: "/grn",
        color: "text-pink-700",
        bgColor: "text-pink-700/10",
        isFileMenu: true,
        subMenu: [
          {
            label: "All GRN",
            icon: LayoutList,
            href: "/category",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },
          {
            label: "New GRN",
            icon: FilePlus2,
            href: "/category",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },

          {
            label: "Analytics",
            icon: PieChart,
            href: "/sub-category",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },
        ],
      },

      {
        label: "RTV",
        icon: Undo2,
        href: "/rtv",
        color: "text-pink-700",
        bgColor: "text-pink-700/10",
        isFileMenu: true,
        subMenu: [
          {
            label: "All RTV",
            icon: LayoutList,
            href: "/category",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },
          {
            label: "New RTV",
            icon: FilePlus2,
            href: "/category",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },

          {
            label: "Analytics",
            icon: PieChart,
            href: "/sub-category",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },
        ],
      },

      {
        label: "Supplier",
        icon: User2,
        href: "/supplier",
        color: "text-pink-700",
        bgColor: "text-pink-700/10",
        isFileMenu: true,
      },
    ],
  },
  {
    label: "Menu & Orders",
    icon: Soup,
    href: "/menu",
    color: "text-orange-700",
    bgColor: "text-orange-700/10",
    isFileMenu: true,
    subMenu: [
      {
        label: "Menu",
        icon: BookOpen,
        href: "/menu/menu-items",
        color: "text-pink-700",
        bgColor: "text-pink-700/10",
        isFileMenu: true,
        subMenu: [
          {
            label: "Menu Items",
            icon: LayoutList,
            href: "/menu/menu-items",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },
          {
            label: "Category",
            icon: Package,
            href: "/menu/menu-category",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },
          {
            label: "Sub Category",
            icon: Boxes,
            href: "/menu/menu-sub-category",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },
        ],
      },
      {
        label: "Orders",
        icon: FileText,
        href: "/order",
        color: "text-pink-700",
        bgColor: "text-pink-700/10",
        isFileMenu: true,
        subMenu: [
          {
            label: "All Orders",
            icon: LayoutList,
            href: "/order",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },
          {
            label: "New Order",
            icon: FilePlus2,
            href: "/order/new-order",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },

          {
            label: "Analytics",
            icon: PieChart,
            href: "/order/sub-category",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },
        ],
      },
    ],
  },
  {
    label: "Table & Booking",
    icon: Container,
    href: "/booking",
    color: "text-sky-500",
    bgColor: "text-sky-500/10",
    isFileMenu: true,
    subMenu: [
      {
        label: "Booking",
        icon: FileText,
        href: "/purchase",
        color: "text-pink-700",
        bgColor: "text-pink-700/10",
        isFileMenu: true,
        subMenu: [
          {
            label: "All Bookings",
            icon: LayoutList,
            href: "/category",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },
          {
            label: "New Booking",
            icon: FilePlus2,
            href: "/category",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },

          {
            label: "Analytics",
            icon: PieChart,
            href: "/sub-category",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },
        ],
      },
      {
        label: "Floors",
        icon: BookOpen,
        href: "/purchase",
        color: "text-pink-700",
        bgColor: "text-pink-700/10",
        isFileMenu: true,
      },
      {
        label: "Table",
        icon: FileText,
        href: "/purchase",
        color: "text-pink-700",
        bgColor: "text-pink-700/10",
        isFileMenu: true,
      },
    ],
  },
  {
    label: "Accounts",
    icon: Calculator,
    href: "/accounts",
    color: "text-green-500",
    bgColor: "text-green-500/10",
    isFileMenu: true,
    subMenu: [
      {
        label: "Incomes",
        icon: BookPlus,
        href: "/purchase",
        color: "text-pink-700",
        bgColor: "text-pink-700/10",
        isFileMenu: true,
      },
      {
        label: "Expences",
        icon: FileMinus,
        href: "/purchase",
        color: "text-pink-700",
        bgColor: "text-pink-700/10",
        isFileMenu: true,
      },

      {
        label: "Ledger",
        icon: Book,
        href: "/sub-category",
        color: "text-pink-700",
        bgColor: "text-pink-700/10",
        isFileMenu: true,
      },
      {
        label: "Setting",
        icon: Cog,
        href: "/accounts",
        color: "text-green-500",
        bgColor: "text-green-500/10",
        isFileMenu: true,
        subMenu: [
          {
            label: "Accounts Head",
            icon: Wallet2,
            href: "/purchase",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },
          {
            label: "Bank",
            icon: Landmark,
            href: "/purchase",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },
          {
            label: "MFS",
            icon: SmartphoneCharging,
            href: "/purchase",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },
        ],
      },
      {
        label: "Analytics",
        icon: PieChart,
        href: "/sub-category",
        color: "text-pink-700",
        bgColor: "text-pink-700/10",
        isFileMenu: true,
      },
    ],
  },
  {
    label: "Inventory",
    icon: ArchiveIcon,
    href: "/inventory",
    color: "text-purple-500",
    bgColor: "text-purple-500/10",
    isFileMenu: true,
    subMenu: [
      {
        label: "All Inventories",
        icon: LayoutList,
        href: "/purchase",
        color: "text-pink-700",
        bgColor: "text-pink-700/10",
        isFileMenu: true,
      },
      {
        label: "Damage",
        icon: Trash2,
        href: "/purchase",
        color: "text-pink-700",
        bgColor: "text-pink-700/10",
        isFileMenu: true,
        subMenu: [
          {
            label: "All Damage",
            icon: LayoutList,
            href: "/category",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },
          {
            label: "New Damage",
            icon: FilePlus2,
            href: "/category",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },

          {
            label: "Analytics",
            icon: PieChart,
            href: "/sub-category",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },
        ],
      },
      {
        label: "Adjustment",
        icon: SlidersHorizontal,
        href: "/purchase",
        color: "text-pink-700",
        bgColor: "text-pink-700/10",
        subMenu: [
          {
            label: "All Adjustment",
            icon: LayoutList,
            href: "/category",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },
          {
            label: "New Adjustment",
            icon: FilePlus2,
            href: "/category",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },

          {
            label: "Analytics",
            icon: PieChart,
            href: "/sub-category",
            color: "text-pink-700",
            bgColor: "text-pink-700/10",
            isFileMenu: true,
          },
        ],
        isFileMenu: true,
      },
      {
        label: "Analytics",
        icon: PieChart,
        href: "/sub-category",
        color: "text-pink-700",
        bgColor: "text-pink-700/10",
        isFileMenu: true,
      },
    ],
  },
  {
    label: "Reports",
    icon: LineChart,
    href: "/reports",
    color: "text-pink-500",
    bgColor: "text-pink-500/10",
    isFileMenu: false,
  },
  {
    label: "User",
    icon: User,
    href: "/user",
    color: "text-emerald-500",
    bgColor: "text-emerald-500/10",
    isFileMenu: false,
  },
  {
    label: "Setting",
    icon: Settings,
    href: "/settings",
    color: "text-zinc-200",
    bgColor: "text-zinc-200/10",
    isFileMenu: false,
    subMenu: [
      {
        label: "App Setting",
        icon: FolderCog,
        href: "/purchase",
        color: "text-pink-700",
        bgColor: "text-pink-700/10",
        isFileMenu: true,
      },
      {
        label: "Profile Setting",
        icon: UserCog,
        href: "/purchase",
        color: "text-pink-700",
        bgColor: "text-pink-700/10",
        isFileMenu: true,
      },
    ],
  },
];
